#!/bin/sh

set -e

bundle install

rm -rf berks-cookbooks
bundle exec berks vendor

if ! vagrant plugin list | grep -q vagrant-omnibus; then
    vagrant plugin install vagrant-omnibus
fi

vagrant up
vagrant reload --provision
vagrant ssh-config > .ssh_config
